name: Delete doc comment

on:
  workflow_run:
    workflows: ["Delete doc comment trigger"]
    types:
      - completed

jobs:
  delete:
    uses: huggingface/doc-builder/.github/workflows/delete_doc_comment.yml@2f8115f4d677905552b45ae1a67c799759fc8001  # main
    secrets:
      comment_bot_token: ${{ secrets.COMMENT_BOT_TOKEN }}