name: Delete doc comment trigger

on:
  pull_request:
    types: [ closed ]

jobs:
  delete:
    uses: huggingface/doc-builder/.github/workflows/delete_doc_comment_trigger.yml@2f8115f4d677905552b45ae1a67c799759fc8001  # main
    with:
      pr_number: ${{ github.event.number }}