name: Rust

on:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        toolchain: [stable]
        include:
          - os: ubuntu-latest
            toolchain: "1.86"
    defaults:
      run:
        working-directory: ./safetensors

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

      - name: Install Rust Stable
        uses: dtolnay/rust-toolchain@d1031067263f94b142dd6c0ce24c5eb9d02d52a0  # stable
        with:
          components: rustfmt, clippy, llvm-tools-preview
          override: true

      - uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6  # v2.9.2

      - name: Install cargo-audit
        run: cargo install cargo-audit

      - name: Build
        run: cargo build --locked --all-targets --verbose

      - name: Lint with Clippy
        run: cargo clippy --locked --all-targets -- -D warnings

      - name: Run Tests
        run: cargo test --locked --verbose

      - name: Run No-STD Tests
        run: cargo test --locked --no-default-features --verbose

      - name: Run Audit
        # RUSTSEC-2021-0145 is criterion so only within benchmarks
        run: cargo audit -D warnings --ignore RUSTSEC-2021-0145
